version: '3.1'

volumes:
  stube_db: {}

services:
  db:
    image: postgres
    restart: always
    volumes:
      - stube_db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev -d devdb']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
