version: '2'

services:
  webserver:
    image: nginx
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/src/static:/static
    ports:
      - 80:80
      - 81:81
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/src/:/app/
    restart: always
    ports:
      - 3000:3000
    command:
      - bash
      - -c
      - ls
      # - |
      # yarn build && yarn start

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - DJANGO_DEBUG=TRUE
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    command:
      - bash
      - -c
      - |
        gunicorn --bind 0.0.0.0:8000 main.wsgi:application
    volumes:
      - ./backend/src/:/app/
    ports:
      - 8000:8000
