# Generated by Django 3.2.7 on 2021-10-03 14:28

import django.contrib.postgres.search
from django.db import migrations, models
import thlog.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(db_index=True, default=thlog.utils.gen_pk, editable=False, max_length=60, primary_key=True, serialize=False, unique=True)),
                ('hide', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('text', models.TextField(max_length=20000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPkTaggedItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=60, verbose_name='object ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(db_index=True, default=thlog.utils.gen_pk, editable=False, max_length=60, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.CharField(db_index=True, default=thlog.utils.gen_pk, editable=False, max_length=60, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=20000)),
                ('hide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(db_index=True, default=thlog.utils.gen_pk, editable=False, max_length=60, primary_key=True, serialize=False, unique=True)),
                ('public', models.BooleanField(default=True)),
                ('closed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('sv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.CharField(db_index=True, default=thlog.utils.gen_pk, editable=False, max_length=60, primary_key=True, serialize=False, unique=True)),
                ('desc', models.CharField(default=None, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
