# Generated by Django 3.2.7 on 2021-10-05 09:43

from django.db import migrations, models
import django.db.models.deletion
import thlog.models


class Migration(migrations.Migration):

    dependencies = [
        ('thlog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=thlog.models.upload_image_to, validators=[thlog.models.validate_image], verbose_name='comment image')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='thlog.comment')),
            ],
        ),
    ]
