# Generated by Django 3.2.7 on 2021-10-03 14:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.utils.timezone
import thlog_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('avatar', models.ImageField(default=None, null=True, upload_to=thlog_auth.models.upload_avatar_to, validators=[thlog_auth.models.validate_avatar])),
                ('nickname', models.CharField(default=None, max_length=20, null=True)),
                ('introduce', models.CharField(default=None, max_length=300, null=True)),
                ('github', models.CharField(default=None, max_length=50, null=True)),
                ('website', models.CharField(default=None, max_length=200, null=True)),
                ('sv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', thlog_auth.models.UserSearchManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='thloguser',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sv'], name='thlog_auth__sv_99d812_gin'),
        ),
    ]
