# Generated by Django 3.2.7 on 2021-10-04 20:49

from django.db import migrations
import sorl.thumbnail.fields
import thlog_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('thlog_auth', '0002_thloguser_avatar_sm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thloguser',
            name='avatar_sm',
        ),
        migrations.AlterField(
            model_name='thloguser',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default=None, null=True, upload_to=thlog_auth.models.upload_avatar_to, validators=[thlog_auth.models.validate_avatar]),
        ),
    ]
