# Generated by Django 3.2.7 on 2021-10-05 09:43

from django.db import migrations
import django_resized.forms
import thlog_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('thlog_auth', '0003_auto_20211004_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thloguser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=None, force_format='PNG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to=thlog_auth.models.upload_avatar_to),
        ),
    ]
