# Generated by Django 3.2.7 on 2021-10-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thlog_auth', '0004_alter_thloguser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thloguser',
            name='website',
            field=models.URLField(default=None, null=True),
        ),
    ]
